server:
  port: 8080

spring:
  application:
    name: resign-system
  servlet:
    multipart:
      max-file-size: 500MB      # 单个文件最大大小（支持大型安装包）
      max-request-size: 500MB   # 整个请求最大大小
      enabled: true
  
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/resign_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: mx)W-)YDkv.b6nE;
  
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
      timeout: 10s
  
  # RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 3
        max-concurrency: 10

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.example.resign.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# MinIO配置
minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: resign-apps
  urlMode: proxy  # 文件访问方式: proxy(代理访问), direct(直接访问), presigned(预签名URL)

# 自定义文件上传配置
file:
  upload:
    avatar-max-size: 2097152      # 头像最大大小 2MB
    file-max-size: 10485760       # 普通文件最大大小 10MB  
    package-max-size: 524288000   # 安装包最大大小 500MB

# 重签名配置
resign:
  # 临时文件存储路径
  temp-dir: /tmp/resign
  # 签名工具路径
  tools:
    ios:
      sign-tool: /usr/bin/codesign
      verify-tool: /usr/bin/codesign
    android:
      sign-tool: /usr/local/bin/apksigner
      zipalign-tool: /usr/local/bin/zipalign
# harmony 配置已移除，专注于 iOS 和 Android
  # 任务配置
  task:
    retry-count: 3
    timeout-seconds: 1800